# Generated by Django 5.2 on 2025-05-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('products', '0003_user_alter_cartmanagement_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
